Changes for upstream quickstart-hashicorp-consul changes
aws-quickstart/quickstart-hashicorp-vault pull request #6
Opened 2017-03-19 23:49 UTC by clstokes

This PR contains complementary changes to https://github.com/aws-quickstart/quickstart-hashicorp-consul/pull/8.

In addition to the changes in PR for quickstart-hashicorp-consul, this PR does the following...

1. Updates Vault to latest version
1. Fixes Vault listener address
1. Specifically enables and starts awslogs service
1. Uses the [ec2-retry](https://www.consul.io/docs/agent/options.html#_retry_join_ec2_tag_key) functionality to join Consul agents
1. Moves all nodes to private subnets
1. Uses Linux Bastion stack to provide bastion box access
1. Updates the AMIs in use to Ubuntu 16.04

2017-03-19 23:52 UTC, clstokes commented
Same as my comment [here](https://github.com/aws-quickstart/quickstart-hashicorp-consul/pull/8#issuecomment-287657719), the templates could use some auto-formatting. Let me know the best way to do this - as a part of this PR or post-merge.

2017-03-20 22:39 UTC, tonynv requested changes
@clstokes The Bastion1/2PrivateIP are hard coded. to 172.31.x.x  subnets.  Please update to use default provided in bastion template.

2017-03-20 23:12 UTC, clstokes commented
@avattathil do you mean these lines specifically? 

https://github.com/clstokes/quickstart-hashicorp-vault/blob/f-consul-ec2-retry/templates/quickstart-hashicorp-vault-master.template#L137

2017-03-20 23:26 UTC, tonynv approved these changes

2017-04-12 23:37 UTC, merged